<?php 
$vision_content  = isset($site_settings['school']['vision']) ? trim($site_settings['school']['vision']) : '';
$mission_content = isset($site_settings['school']['mission']) ? trim($site_settings['school']['mission']) : '';

// Content-Driven Rendering Principle:
// Render section ONLY if real vision or mission content exists in CMS.
// No hardcoded or fictional institutional text is generated by the Theme.
if (!empty($vision_content) || !empty($mission_content)):
?>
<!-- Vision & Mission Component -->
<section class="py-16 sm:py-20 bg-slate-50 relative overflow-hidden border-b border-emerald-100">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
        <div class="text-center max-w-2xl mx-auto space-y-3">
            <span class="text-xs font-bold uppercase tracking-widest text-emerald-700 bg-emerald-100/60 px-3.5 py-1 rounded-full border border-emerald-200">
                <?php echo !empty($hp_vision_subtitle) ? esc_html($hp_vision_subtitle) : 'Landasan Pendidikan'; ?>
            </span>
            <h2 class="text-3xl sm:text-4xl font-extrabold tracking-tight text-emerald-950">
                <?php echo !empty($hp_vision_title) ? esc_html($hp_vision_title) : 'Visi &amp; Misi Sekolah'; ?>
            </h2>
            <p class="text-slate-600 text-sm sm:text-base">Komitmen dan pedoman kami dalam mendidik generasi penerus bangsa.</p>
        </div>

        <div class="grid md:grid-cols-2 gap-8">
            <?php if (!empty($vision_content)): ?>
            <!-- Visi Card -->
            <div class="bg-white rounded-3xl p-8 border border-emerald-100 shadow-md hover:shadow-xl transition duration-300 space-y-4 relative <?php echo empty($mission_content) ? 'md:col-span-2' : ''; ?>">
                <div class="w-14 h-14 rounded-2xl bg-emerald-50 text-emerald-700 flex items-center justify-center border border-emerald-100 shadow-sm">
                    <i data-lucide="compass" class="w-7 h-7"></i>
                </div>
                <h3 class="text-2xl font-extrabold text-emerald-950">Visi Sekolah</h3>
                <div class="text-slate-700 text-base leading-relaxed font-medium">
                    <?php echo nl2br(esc_html($vision_content)); ?>
                </div>
            </div>
            <?php endif; ?>

            <?php if (!empty($mission_content)): ?>
            <!-- Misi Card -->
            <div class="bg-white rounded-3xl p-8 border border-emerald-100 shadow-md hover:shadow-xl transition duration-300 space-y-4 relative <?php echo empty($vision_content) ? 'md:col-span-2' : ''; ?>">
                <div class="w-14 h-14 rounded-2xl bg-amber-50 text-amber-600 flex items-center justify-center border border-amber-100 shadow-sm">
                    <i data-lucide="target" class="w-7 h-7"></i>
                </div>
                <h3 class="text-2xl font-extrabold text-emerald-950">Misi Sekolah</h3>
                <div class="text-slate-600 text-sm leading-relaxed space-y-2">
                    <?php echo nl2br(esc_html($mission_content)); ?>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>
</section>
<?php endif; ?>

